services:
  - type: web
    name: api-resolutor
    env: python
    plan: free
    rootDir: api-resolutor
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000

  - type: web
    name: registro-usuarios
    env: python
    plan: free
    rootDir: register
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
